spring.application.name=payment
spring.datasource.url=jdbc:mysql://localhost:3306/paymentDB
spring.datasource.username=root
spring.datasource.password=Aamishsql@7055
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.data.redis.host=localhost
spring.data.redis.port=6379